//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class si2Entities : DbContext
    {
        public si2Entities()
            : base("name=si2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Fornecedor> Fornecedors { get; set; }
        public virtual DbSet<Franqueado> Franqueadoes { get; set; }
        public virtual DbSet<Franqueado_Vende_Produto> Franqueado_Vende_Produto { get; set; }
        public virtual DbSet<Info_Anual> Info_Anual { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<TudoSobreProduto> TudoSobreProdutoes { get; set; }
    
        public virtual int franq_del(Nullable<decimal> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("franq_del", idParameter);
        }
    
        public virtual int franq_in(Nullable<decimal> id, Nullable<decimal> nif, string nome, string morada)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            var nifParameter = nif.HasValue ?
                new ObjectParameter("nif", nif) :
                new ObjectParameter("nif", typeof(decimal));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("morada", morada) :
                new ObjectParameter("morada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("franq_in", idParameter, nifParameter, nomeParameter, moradaParameter);
        }
    
        public virtual int franq_up(Nullable<decimal> id, Nullable<decimal> nif, string nome, string morada)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            var nifParameter = nif.HasValue ?
                new ObjectParameter("nif", nif) :
                new ObjectParameter("nif", typeof(decimal));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var moradaParameter = morada != null ?
                new ObjectParameter("morada", morada) :
                new ObjectParameter("morada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("franq_up", idParameter, nifParameter, nomeParameter, moradaParameter);
        }
    
        public virtual int franq_vende_new_product(string codigo, Nullable<decimal> id, Nullable<int> min_stock, Nullable<int> max_stock, Nullable<int> stock_atual, Nullable<decimal> preco, Nullable<int> venda_ano_atual, Nullable<System.DateTime> data_ultima_venda)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            var min_stockParameter = min_stock.HasValue ?
                new ObjectParameter("min_stock", min_stock) :
                new ObjectParameter("min_stock", typeof(int));
    
            var max_stockParameter = max_stock.HasValue ?
                new ObjectParameter("max_stock", max_stock) :
                new ObjectParameter("max_stock", typeof(int));
    
            var stock_atualParameter = stock_atual.HasValue ?
                new ObjectParameter("stock_atual", stock_atual) :
                new ObjectParameter("stock_atual", typeof(int));
    
            var precoParameter = preco.HasValue ?
                new ObjectParameter("preco", preco) :
                new ObjectParameter("preco", typeof(decimal));
    
            var venda_ano_atualParameter = venda_ano_atual.HasValue ?
                new ObjectParameter("venda_ano_atual", venda_ano_atual) :
                new ObjectParameter("venda_ano_atual", typeof(int));
    
            var data_ultima_vendaParameter = data_ultima_venda.HasValue ?
                new ObjectParameter("data_ultima_venda", data_ultima_venda) :
                new ObjectParameter("data_ultima_venda", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("franq_vende_new_product", codigoParameter, idParameter, min_stockParameter, max_stockParameter, stock_atualParameter, precoParameter, venda_ano_atualParameter, data_ultima_vendaParameter);
        }
    
        public virtual int printTotalPrice(Nullable<decimal> id_costumer)
        {
            var id_costumerParameter = id_costumer.HasValue ?
                new ObjectParameter("id_costumer", id_costumer) :
                new ObjectParameter("id_costumer", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("printTotalPrice", id_costumerParameter);
        }
    
        public virtual int prod_del_product_and_franqueado(string codigo, Nullable<decimal> id_franqueado)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var id_franqueadoParameter = id_franqueado.HasValue ?
                new ObjectParameter("id_franqueado", id_franqueado) :
                new ObjectParameter("id_franqueado", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prod_del_product_and_franqueado", codigoParameter, id_franqueadoParameter);
        }
    
        public virtual int prod_in(string codigo, string descricao, Nullable<int> min_stock, Nullable<int> max_stock, Nullable<int> stock_atual, string tipo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("descricao", descricao) :
                new ObjectParameter("descricao", typeof(string));
    
            var min_stockParameter = min_stock.HasValue ?
                new ObjectParameter("min_stock", min_stock) :
                new ObjectParameter("min_stock", typeof(int));
    
            var max_stockParameter = max_stock.HasValue ?
                new ObjectParameter("max_stock", max_stock) :
                new ObjectParameter("max_stock", typeof(int));
    
            var stock_atualParameter = stock_atual.HasValue ?
                new ObjectParameter("stock_atual", stock_atual) :
                new ObjectParameter("stock_atual", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prod_in", codigoParameter, descricaoParameter, min_stockParameter, max_stockParameter, stock_atualParameter, tipoParameter);
        }
    
        public virtual int product_purchase(string codigo, Nullable<decimal> id_costumer, Nullable<int> quantity)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var id_costumerParameter = id_costumer.HasValue ?
                new ObjectParameter("id_costumer", id_costumer) :
                new ObjectParameter("id_costumer", typeof(decimal));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("product_purchase", codigoParameter, id_costumerParameter, quantityParameter);
        }
    }
}
