//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TudoSobreProduto
    {
        public string codigo_prd { get; set; }
        public Nullable<int> min_stock { get; set; }
        public Nullable<int> max_stock { get; set; }
        public Nullable<int> stock_atual { get; set; }
        public decimal preco { get; set; }
        public Nullable<int> venda_ano_atual { get; set; }
        public Nullable<System.DateTime> data_ultima_venda { get; set; }
    }
}
